### ISSUE TITLE
Reporting commit from last to current deploy instead of current one

### ISSUE THREAD

**Issue by warrenguy** [Flink/dokku-airbrake-deploy#1]
For me, this seems to be reporting to Airbrake the commit id/message of the last to current deploy, rather than the current one. However if I `dokku ps:restart` the app, the correct commit is reported to Airbrake. Running the same `git log` commands in the app's directory on the dokku server reports the correct commit. I can't see any obvious reason for this to be occurring.

Probably an issue with dokku itself I guess? Just wondering if anyone else has seen this behaviour.

I'm using Dokku v0.3.17.

**Comment by Flink** [comment]
Sorry for the delay, I’m taking a look right now :)

**Comment by Flink** [comment]
This issue should be fixed with the latest master :)

**Comment by warrenguy** [comment]
Excellent, works perfectly now. Thank you!
